### PR TITLE
Check running app

### PR DESCRIPTION
**Pull request by pegatron89**
I have added a function to check if there are any apps currently running on the TV. Currently it works but only checks between plex netflix and youtube.

### CODE REVIEW

**Comment by jaruba** [comment]
There must be some better way to do this then spamming the TV with requests.

The thing that worries me here is that if we add 20 such apps, the TV might block requests from our HA IP. I've seen TVs block network IPs before for DLNA discovery abuse, so it's not far fetched..

But we could still use this on a small scale of popular apps.. like Spotify, Youtube, Amazon Prime, Netflix, etc.

**Comment by jaruba** [comment]
Regardless, I promise I'll test it and merge by tomorrow, it's a good feature, thanks for the PR!

**Comment by pegatron89** [comment]
I thought the same that is why i limited it to 3 apps, Thought it might be an idea to add a "fave_apps:" to configuration and only scan they pre-determined apps. There must be a way for the TV reporting back HDMI as well, The samsung app on the phone shows HDMI 1 or HDMI 2 depending which source i am on.

**Comment by jaruba** [comment]
@pegatron89 I've thought about this more, I don't think we need a `fave_apps:` property, we can use the current `app_list:` property for this.

Presuming the value:
```
app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'
```

Would only check for `Netflix`, `YouTube` and `Spotify`.

**Comment by jaruba** [comment]
Merging and adding a few changes

**Comment by jaruba** [comment]
I've tested it on my 2 Samsung TVs, made a few minor changes and published a new release.

**Comment by pegatron89** [comment]
Tried this and getting an error:

019-12-24 12:51:55 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 319, in source_list
    self._gen_installed_app_list()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 229, in _gen_installed_app_list
    app_list = self._remote.app_list()
TypeError: 'NoneType' object is not callable

No longer loads up either of my TV's either.

I will have another try when im home

**Comment by jaruba** [comment]
Well, shit. It seems to work for my two TV sets, but I did notice some issues. With the newer TV model, when the TV is turned off, it never replies to the requests, hanging the entire process for a long time, it's why I set the 5 second timer.

And it made both TV sets change the `on` / `off` states a lot slower for some reason.

**Comment by pegatron89** [comment]
Still getting the same error with your latest version. Tried again just now, Reverted back to mine an all worked ok again. 

The state takes 1 minute exactly to update on each TV. Just using the defaults

**Comment by jaruba** [comment]
Do you set `app_list`? I think that might be the reason for the error.

**Comment by pegatron89** [comment]
I installed removed my version and re-installed yours, Added an app_list to my configuration copy and pasted from your readme and now get:

> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
>     await entity.async_update_ha_state()
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
>     attr.update(self.state_attributes or {})
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
>     for attr in ATTR_TO_PROPERTY
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
>     if getattr(self, attr) is not None
>   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 336, in source
>     self._source = self._remote.get_running_app()
>   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 235, in get_running_app
>     appState = root[2].text
>   File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 217, in __getitem__
>     return self._children[index]
> IndexError: list index out of range

Is it using the app name "Plex" or using the number? If you browse to ip:8080/ws/app/{app_number} it wont work, It will only work with Plex, YouTube, Netflix etc

**Comment by jaruba** [comment]
I've made a new release, please try it.

**Comment by jaruba** [comment]
it should use the names, not the numbers

**Comment by jaruba** [comment]
can you also please show me the config you're using with this component?

it might help reproduce the errors you're getting

**Comment by pegatron89** [comment]
Sorry but the new update doesnt give me the same error as before but also doesnt bring back the current app either. The only error i can see in the error log is:

> 2019-12-26 22:11:50 DEBUG (SyncWorker_9) [custom_components.samsungtv_custom.media_player] Error in send_command() -> OSError

My current configs are:

TV type:  UE55NU7100 (living Room) & Bedroom: UE49MU6400

`media_player:
  - platform: samsungtv_custom
    host: 192.168.0.9
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'
    mac: XXXXXXXX
    port: 8002
    name: Living Room TV
  - platform: samsungtv_custom
    host: 192.168.0.6
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'
    mac: XXXXXXXX
    port: 8002
    name: Bedroom TV
`

**Comment by jaruba** [comment]
Did you "Allow" the HA connection on the TVs again after the update? This needs to be done (maybe numerous times) after the component update.

**Comment by jaruba** [comment]
Also try restarting HA a second time.

**Comment by pegatron89** [comment]
yeah had to allow it 2 more times. Then tried deleting the __pycache__ restarting HA again just now

**Comment by jaruba** [comment]
I'm also thinking of using [grequests](https://github.com/spyoungtech/grequests), because that would make the requests async and reduce the update time. Currently the requests are synchronous so they are done one after the other, as opposed to all being done at the same time.

**Comment by pegatron89** [comment]
Updating state for media_player.living_room_tv (<class 'custom_components.samsungtv_custom.media_player.SamsungTVDevice'>) took 0.934 seconds. Please report platform to the developers at https://goo.gl/Nvioub


Same error on both TVs

**Comment by jaruba** [comment]
Yeah, i get that too, but it should work anyway. It's a warning, not an error. That time can be reduced a lot if we use async requests.

Also, if you set an app in `app_list` that the TV does note have installed, it will make the requests for that app's data longer then normal.

You also won't see Plex as running, because you didn't set it in `app_list`.

**Comment by jaruba** [comment]
Here is a list of Tizen App IDs (it includes Plex's):
https://github.com/tavicu/homebridge-samsung-tizen/issues/26#issuecomment-447424879

**Comment by jaruba** [comment]
You can also do tests without setting `app_list` at all now, (and it _should_ autogenerate the app list) as the bug that caused that initial error has been fixed now.

**Comment by pegatron89** [comment]
No errors after adding plex but still not getting back any source.

State attributes

```
volume_level: 0.13
is_volume_muted: false
source_list:
  - TV
  - HDMI
  - Netflix
  - YouTube
  - Plex
friendly_name: Living Room TV
supported_features: 20413
device_class: tv
```

**Comment by jaruba** [comment]
If you add `print('http://{host}:8080/ws/app/{app}'.format(host=self.host, app=app))` to this line:
https://github.com/jaruba/ha-samsungtv-custom/blob/master/custom_components/samsungtv_custom/samsungtvws/remote.py#L224

And set `logger` to `info` for this component:
https://www.home-assistant.io/integrations/logger/

You should be able to see exactly what request URLs are used in your logs.

**Comment by jaruba** [comment]
Interesting thing I discovered is that if we do a GET request to `http://{host}:8080/ws/app/{app}`, then it gets the app data.

But if we do a POST request to the exact same URL, it starts that app, without needing any App ID, just the correct name of the app..

**Comment by pegatron89** [comment]
My code for the function is:

```
    def get_running_app(self):

        if self._app_list is not None:

            for app in self._app_list:

              r = None
              print('http://{host}:8080/ws/app/{app}'.format(host=self.host, app=app))
              try:
                r = requests.get('http://{host}:8080/ws/app/{app}'.format(host=self.host, app=app), timeout=2)
              except requests.exceptions.RequestException as e:
                pass

              if r is not None:
                  data = r.text
                  if data is not None:
                      root = ET.fromstring(data.encode('UTF-8'))
                      appName = root[0].text
                      appState = root[2].text
                      if appState == "running":
                        return app

```

and my config is:

```
logger:
  logs:
    custom_components.samsungtv_custom: info
```

Still not getting anything back or anything in the log either. 


Tried the POST request using only the app name and it started the app as well. 

If only there was a way of detecting which HDMI it was on, In the samsung app on my phone it can  tell if the TV is on HDMI1 or 2 so i think there must be something on the TV reporting it back somewhere

**Comment by jaruba** [comment]
I keep poking in their API, i also found that:
`http://{host}:8080/ws/app/{app}`
and:
`http://{host}:8080/ws/apps/{app}`
both do the same thing (notice `apps` instead of `app`)

I also found this:
`http://{host}:8001/api/v2/applications/{app_id}`

Also gets similar app data info based on app id:
```
{"id":"11101200001","name":"Netflix","running":false,"version":"7.0.000","visible":true}
```

This last one (with the app id) actually seems to be the recommended way, because 2016+ TVs introduced this api on port `8001` and `8002`, and this component is for 2016+ TVs.

**Comment by pegatron89** [comment]
Nice! That could maybe work a bit better then using port 8001 / 8002 , Thats what everything else runs on

**Comment by jaruba** [comment]
I made a new release using the new api endpoint, it works better for me, you should try it.

**Comment by jaruba** [comment]
Funny story, i found this issue thread:
https://github.com/Ape/samsungctl/issues/75

That seems to explain many possible endpoints for the various Tizen APIs, and you commented in this thread more then 1 yr and a half ago 🤣

**Comment by pegatron89** [comment]
Works for me this morning as well! Thanks again!

Just read through the thread there, I stopped using HA for a while and forgot all about that.

**Comment by jaruba** [comment]
There are a few things I learned from that issue thread:

- The App ID doesn't need to be a number, any of these IDs also work: https://github.com/Ape/samsungctl/issues/75#issuecomment-404941201

- There is [a list of supported methods](https://github.com/Ape/samsungctl/issues/75#issuecomment-446778145) for the WS API, one such method also gets app related data, I'm thinking it may be an ever better way of getting the running app

I still found nothing related to knowing what input source is being used (TV, HDMI1, etc), which is sad because I really want those to work too..

**Comment by jaruba** [comment]
I made a new release that further reduces the request timeout to 0.5 seconds, which seems to make the state update much faster and I haven't seen it not work yet. I've also set the state to "TV/HDMI" when no app if found running.

Until I get some more relevant info from these hidden APIs, this will have to do..

**Comment by pegatron89** [comment]
Tried the latest version again, I am getting the state back only on TV/HDMI, Plex is running on the TV at the moment

```
 [custom_components.samsungtv_custom.media_player] Failed sending payload KEY command_type send_key
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 102, in recv
    bytes_ = _recv()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 84, in _recv
    return sock.recv(bufsize)
  File "/usr/lib/python3.7/ssl.py", line 1037, in recv
    return self.read(buflen)
  File "/usr/lib/python3.7/ssl.py", line 913, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/media_player.py", line 262, in send_command
    self._remote.send_key(payload)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 140, in send_key
    self._ws_send(payload)
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 93, in _ws_send
    self.open()
  File "/home/homeassistant/.homeassistant/custom_components/samsungtv_custom/samsungtvws/remote.py", line 111, in open
    response = json.loads(self.connection.recv())
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 313, in recv
    opcode, data = self.recv_data()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 330, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 343, in recv_data_frame
    frame = self.recv_frame()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 377, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 452, in _recv
    return recv(self.sock, bufsize)
  File "/srv/homeassistant/lib/python3.7/site-packages/websocket/_socket.py", line 105, in recv
    raise WebSocketTimeoutException(message)
```

**Comment by pegatron89** [comment]
I am just getting a constant TV/HDMI now for the state. It can still change the source but just won't update the state. No errors in the logs either.

**Comment by pegatron89** [comment]
ignore that, I had the wrong commit. Latest one works perfect, and is a lot faster at updating the state as well!

Now hopefully find a way for current HDMi source lol or even be able to change direct to desired HDMI rather than toggle between them.

Thanks for this though!

**Comment by xssj2020** [comment]
Hey jaruba, sorry for hijacking this topic, but it was the closest I could find.
I just wanted to say thanks for your great home assistant plugin and share some more applist ids from a German QLED 2018 user.

{'Prime Video': '3201512006785', 'Spotify': '3201606009684', 'YouTube': '111299001912', 'Netflix': '11101200001', 'MagentaSport': '3201707014358', 'Joyn': '3201502001386', 'Steam Link': '3201702011851', 'ZDF mediathek': '3201705012365', 'Universal Guide': '3201710015067', 'ProSieben': '3201608010221', 'sixx': '3201608010224', 'ARD Mediathek': '3201412000679', 'Apple TV': '3201807016597', 'SmartThings': '3201710015016', 'TV DIGITAL': '3201602007987', 'Sky Q': '3201802015776', 'Sky Ticket': '3201411000562', 'Internet': 'org.tizen.browser', 'Google Play Filme': '3201601007250', 'Rakuten TV': '3201511006428', 'Gallery': '3201710015037', 'waipu.tv – Fernsehen wie noch nie': '3201804016033', 'PrivacyChoices': '3201909019271', 'Disney+': '3201901017640', 'DW for Smart TV': '3201511006303', 'SeeColors': '3201604009179', 'Eurosport Player': '3201703012079', 'e-Manual': '20182100010', 'maxdome': '3201803015887', 'Sportworld': '3201803015972', 'McAfee Security for TV': '3201612011418', 'CHILI': '3201505002690', 'DAZN': '3201607009920', 'Zattoo': '111299001432', 'Samsung SportWorld': '3201903018105', 'Red Bull TV': '3201602007756', 'Apple Music': '3201908019041', 'Couchplay SpieleCenter': '3201609010528', 'TVNOW PREMIUM': '3201908018988', 'Audi': '11111358501', 'MagentaTV': '3201907018746', 'ARTE': '3202011022316'}

**Pull request merged**
